language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mkdir -p build/logs
  - cp .env.travis .env
  - mysql -e 'create database feature_manager;'
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi

script:
  - php artisan migrate --seed
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - php vendor/bin/php-coveralls -v
